In [ ]:
import pandas as pd

In [7]:
df = pd.read_csv("results/preds_hybrid_conf_2026-08-21T12_46_12_rep1.csv")
df.shape

(148, 10)

In [8]:
df.head()

,mu0,mu1,y0_mean,y1_mean,y0_std,y1_std,y0_lo95,y0_hi95,y1_lo95,y1_hi95
0,-0.741982,1.022022,0.845486,1.166928,5.731791,0.780950,-7.191479,7.191954,-0.457210,2.258209
1,-0.352879,1.173856,1.546127,1.202068,5.703449,0.738128,-7.188639,7.191954,-0.373510,2.404546
2,-0.820336,0.983238,1.930252,1.041924,5.350298,0.883563,-7.189741,7.191954,-0.379335,2.506408
3,-0.502919,1.121752,-0.185070,1.055615,5.607007,1.099172,-7.185894,7.189757,-0.838981,2.992753
4,-0.987506,0.885718,1.136978,0.981533,5.599574,0.903547,-7.159522,7.189894,-0.679823,2.374693

In [6]:
df.describe()

,mu0,mu1,y0_mean,y1_mean,y0_std,y1_std,y0_lo95,y0_hi95,y1_lo95,y1_hi95
count,148.000000,148.000000,148.000000,148.000000,148.000000,148.000000,148.000000,148.000000,148.000000,148.000000
mean,-0.456661,1.093815,0.299718,1.215900,5.590930,0.832134,-7.172349,7.176383,-0.390334,2.542063
std,0.628009,0.182739,0.845195,0.162783,0.257059,0.167744,0.043446,0.064999,0.440850,0.187929
min,-1.147673,0.763769,-1.665754,0.794339,4.851287,0.508352,-7.191954,6.463196,-1.808063,2.038565
25%,-0.870080,0.956562,-0.252575,1.113588,5.461413,0.698227,-7.191954,7.180205,-0.681161,2.409142
50%,-0.617763,1.076854,0.315680,1.227110,5.610491,0.824460,-7.187757,7.189675,-0.382488,2.534182
75%,-0.231622,1.211606,0.894154,1.342417,5.763333,0.953189,-7.176820,7.191954,-0.081998,2.691480
max,2.715451,1.680429,2.426187,1.541695,6.246774,1.269203,-6.884534,7.191954,0.438172,2.992753

In [16]:
sum(df["y0_lo95"] == df["y0_lo95"].min())

46

In [28]:
sum(df["y0_hi95"] == df["y0_hi95"].max())

48